export {CandidatosPage} from './CandidatosPage'
export {PrivacidadPage} from './PrivacidadPage'
export {MostrarInePage} from './MostrarInePage'
export {VotarPage} from './VotarPage'
export {ResultadosPage} from './ResultadosPage.jsx'