export {CandidatoCard} from './CandidatoCard'
export {CandidaturaBtn} from './CandidaturaBtn'
export {ModalPropuestas} from './ModalPropuestas'
export {PoliticasCheckbox} from './PoliticasCheckbox'
export {PoliticaPrivacidadCard} from './PoliticaPrivacidadCard'
export {PoliticasDialog} from './PoliticasDialog'
export {Camera} from './Camera'